name: Docker - Build and push latest

on:
  push:
    branches: [ "**" ]
    tags-ignore: [ "release-*" ]
  workflow_dispatch:


env:
  REGISTRY: ghcr.io
  APP_IMAGE: ghcr.io/${{ github.repository }}/${{ github.ref_name }}/razor-example
  BUILD_IMAGE: ghcr.io/${{ github.repository }}/${{ github.ref_name }}/razor-example:buildimage
  CONTENSIS_CLIENT_ID: 27be5f01-8e84-41af-8f02-26929c6b8457
  CONTENSIS_SHARED_SECRET: 7fb2a6b6a1be4b9d8e72b4a5ad5d3915-46a6a980e4e74b5b810191d03ae3512a-4c360c28c3b74a6ebd21be733752849a

jobs:
  build-latest:
    name: Build Block
    runs-on: ubuntu-latest
    outputs:
      image-uri: ${{ steps.build.outputs.image-uri }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into the container registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image, tag and push to the registry
        id: build
        env:
          APP_IMAGE_URI: ${{ env.APP_IMAGE }}:build-${{ github.run_number }}
        run: |
          chmod +x build.sh
          ./build.sh
          echo "image-uri=$APP_IMAGE_URI" >> $GITHUB_OUTPUT
          echo "Built Successfully"
        shell: bash
  deploy:
    name: Push block to Contensis
    runs-on: ubuntu-latest
    needs: build-latest
    steps:
      - name: Push block to Contensis
        id: push-block
        uses: contensis/block-push@v1
        with:
          block-id: dotnet-blocgrecord-jaro
          alias: velocity-blocks
          project-id: leif14
          client-id: ${{ env.CONTENSIS_CLIENT_ID }}
          shared-secret: ${{ env.CONTENSIS_SHARED_SECRET }}
          image-uri: ${{ env.APP_IMAGE }}:build-${{ github.run_number }}
